### ISSUE TITLE
Form style not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/compatible#10]
https://codesandbox.io/s/adoring-cloud-kmm9w

ref: https://github.com/ant-design/ant-design/issues/19800

**Comment by shaodahong** [comment]
Need import style `import '@ant-design/compatible/assets/index.css'`, and I will update document

**Comment by zombieJ** [comment]
Seems not align after import class file

<img width="410" alt="截屏2019-12-07下午9 36 29" src="https://user-images.githubusercontent.com/5378891/70375527-a927a780-1939-11ea-8cac-c5815de9ef63.png">

**Comment by shaodahong** [comment]
> Seems not align after import class file
> 
> <img alt="截屏2019-12-07下午9 36 29" width="410" src="https://user-images.githubusercontent.com/5378891/70375527-a927a780-1939-11ea-8cac-c5815de9ef63.png">

@zombieJ  In the demo, I only saw `verticaI` mode not align, but in your pic, I saw`Horizontal`?

**Comment by shaodahong** [comment]
not align reason of 4.0 `Grid` use flex by default, In `Vertical` mode, the label should a block

**Comment by ycjcl868** [comment]
@shaodahong the Row, Col in Form have some problems.

https://codesandbox.io/s/strange-sammet-83bz3

![image](https://user-images.githubusercontent.com/13595509/70403192-18ec7e00-1a71-11ea-8cf7-425c24958d33.png)

**Comment by shaodahong** [comment]
@ycjcl868 Will fixes by #13
