### ISSUE TITLE
Form onFieldsChange initialValue 

### ISSUE THREAD

**Issue by yuandapeng** [ant-design/compatible#128]
复现步骤
1.在name文本框输入任意内容触发onFieldsChange
2.查看控制台输出接口allValues中的id字段的initialValue 中初始值不在里面
复现demo：https://codesandbox.io/s/ant-design-compatible-onfieldschange-initialvalue-v3gg2i
期望：可以在onFieldsChange中拿到初始值

**Comment by yuandapeng** [comment]
@PeachScript

**Comment by yuandapeng** [comment]
这个问题更精确一点就是select 组件会发生这样的问题

**Comment by zombieJ** [comment]
的确怪异……

**Comment by zombieJ** [comment]
大致看了一下是 `rc-form` ref 处理逻辑问题，FC 抓不到实体。为了防止 breaking change，`rc-form` 应该是不会动了。

**Comment by yuandapeng** [comment]
我自己再看看吧
