### ISSUE TITLE
Compile issue from v4 to v5

### ISSUE THREAD

**Issue by alenocera** [ant-design/compatible#153]
Hi, 
issue here after compiling:

`Compiled with problems:X
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 2:0-107
export 'FormProps' (reexported as 'FormProps') was not found in './Form' (possible exports: default)
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 2:0-107
export 'FormComponentProps' (reexported as 'FormComponentProps') was not found in './Form' (possible exports: default)
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 2:0-107
export 'FormCreateOption' (reexported as 'FormCreateOption') was not found in './Form' (possible exports: default)
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 2:0-107
export 'ValidateCallback' (reexported as 'ValidateCallback') was not found in './Form' (possible exports: default)
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 2:0-107
export 'ValidationRule' (reexported as 'ValidationRule') was not found in './Form' (possible exports: default)
ERROR in ./node_modules/@ant-design/compatible/es/form/index.js 3:0-43
export 'FormItemProps' (reexported as 'FormItemProps') was not found in './FormItem' (possible exports: default)`

I've used the last package, 5.1.0
I don't know what is happened. Seems all ok in my project, only this one fails. Can somebody check in this export?

Thanks guys!

**Comment by ledge74** [comment]
5.1.1 fixed it for me

**Comment by frrfdev** [comment]
Same problem here, version 5.1.1
