### ISSUE TITLE
ant-design/pro-table 使用了 legacy form 之后样式表不对

### ISSUE THREAD

**Issue by vagusX** [ant-design/compatible#16]
https://github.com/ant-design/pro-table/issues/14

**Comment by shaodahong** [comment]
之前修的没发版的原因，我发了新版

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/71102068-c5a5c880-21f2-11ea-9051-51371afe572b.png)
问题me没有解决，还是有问题。

**Comment by chenshuai2144** [comment]
会搞坏原来的样式。能兼容吗？

**Comment by shaodahong** [comment]
我 fork 代码拉下来使用 `@ant-design/compatible` 替换完全兼容

1. https://github.com/shaodahong/pro-table/blob/677d1e16d29d4b367fb179988b7791fa6a376344/src/Form/index.less#L12
```diff
-.ant-form-item-label {
+.ant-legacy-form-item-label {
    min-width: 80px;
    text-align: right;
  }
-.ant-form-item {
+.ant-legacy-form-item {
    display: flex;
  }

- .ant-form-item-control-wrapper {
+ .ant-legacy-form-item-control-wrapper {
    flex: 1;
  }
```
2. https://github.com/shaodahong/pro-table/blob/677d1e16d29d4b367fb179988b7791fa6a376344/src/Form/index.tsx#L10

```diff
+import { Form } from '@ant-design/compatible';
+import '@ant-design/compatible/assets/index.css'
-import { Input, Form, Row, Col, TimePicker, InputNumber, DatePicker, Select, Button } from 'antd';
+import { Input, Row, Col, TimePicker, InputNumber, DatePicker, Select, Button } from 'antd';
```

**Comment by shaodahong** [comment]
应该避免使用这种修改样式的方式，最好加个自定义的类名

**Comment by shaodahong** [comment]
或者直接梭哈 antd 4.0

**Comment by chenshuai2144** [comment]
ant-legacy-form-explain 
这系列的样式丢掉了  @shaodahong

**Comment by shaodahong** [comment]
> ant-legacy-form-explain
> 这系列的样式丢掉了

@chenshuai2144 

https://github.com/ant-design/compatible/blob/a02c9fe88c0bf5969cae0e5a23abe0b8b3739313/src/form/style/index.less#L113

**Comment by chenshuai2144** [comment]
颜色应该是红色，看样子是红色没了

**Comment by shaodahong** [comment]
嗯，是有 bug 我来搞下
