### ISSUE TITLE
rc 之前需要同步一下 antd 主干的改动

### ISSUE THREAD

**Issue by afc163** [ant-design/compatible#17]
- [x] form
- [x] icon
- [x] mention

**Comment by shaodahong** [comment]
@vagusX Icon 组件你帮忙看下吧，其他两个的改动我来

**Comment by vagusX** [comment]
Icon 需要按照 7月30日之后所有的变更同步到 `@ant-design/icons` 和 `@ant-design/compatible` 两个库里面

**Comment by vagusX** [comment]
已发布 0.0.1-rc.1
