### ISSUE TITLE
在 asset 中未发现有index.css，报错

### ISSUE THREAD

**Issue by hzq001** [ant-design/compatible#21]
- 引用`@ant-design/compatible/assets/index.css`报错
- 在`node_modules` 中未发现该文件
- 版本 ` "@ant-design/compatible": "^0.0.1-alpha.9"`

**Comment by shaodahong** [comment]
![image](https://user-images.githubusercontent.com/14831261/71793861-b1c6e700-3079-11ea-9704-4b4c0be12fcd.png)

**Comment by hzq001** [comment]
![image](https://user-images.githubusercontent.com/12715885/71793902-e63aa300-3079-11ea-8585-d20539525423.png)

**Comment by shaodahong** [comment]
你的 README 也是没有的，是不是安装了什么过滤软件，我记得有个过滤软件是可以过滤下载包中无用的文档，来达到减少本地的开发环境大小

**Comment by afc163** [comment]
https://unpkg.com/browse/@ant-design/compatible@0.0.1-alpha.9/ 是有的。

**Comment by hzq001** [comment]
- 这个没有的啊，我都是在用 `yarn` 还有就是 pro 的那些插件
- 使用的是  `https://registry.npm.taobao.org` 源

**Comment by afc163** [comment]
你可以先换 npm 或者 cnpm 试试。

**Comment by hzq001** [comment]
经过实测使用 yarn 是不行的，使用 npm 就可以了

**Comment by afc163** [comment]
yarn 版本是不是太老了。

**Comment by hzq001** [comment]
- 1.19.2

**Comment by afc163** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/507615/71797407-f148ff80-3088-11ea-8b3b-be45e1dd75d7.png">

yarn@1.21.1 表示没问题。

**Comment by hzq001** [comment]
这个应该跟 yarn 版本无关，我有试了 yarn@1.21.1 还是存在该问题。我所有的包都是没有 README 的，我没有另外配置过滤插件，都是使用 umi 新版

**Comment by hzq001** [comment]
![image](https://user-images.githubusercontent.com/12715885/71803884-e39d7500-309c-11ea-9447-b61e183f5e72.png)
经过排查是我这边 `.yarnclean` 文件配置了清除 `assets` 文件，导致每次都会删除该文件。
