### ISSUE TITLE
Theme customizations are missing for @ant-design/compatible

### ISSUE THREAD

**Issue by severi** [ant-design/compatible#46]
Is there a way to keep the theme customizations done by overriding the less-variables as described here https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables when using @ant-design/compatible

We used them quite a bit for version 3, and now that we have migrated to version 4 and use the @ant-design/compatible the overrides don't work anymore.

**Comment by afc163** [comment]
We need original less file in https://unpkg.com/browse/@ant-design/compatible@1.0.2/assets/
